# Generated by Django 4.2.5 on 2023-09-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('species', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('rabbit', 'Rabbit')], max_length=6)),
            ],
        ),
    ]
